using System.Collections.Generic;
using System.Windows;

namespace KLC_Finch {
    /// <summary>
    /// Interaction logic for WindowEventsExtended.xaml
    /// </summary>
    public partial class WindowEventsExtended : Window {

        public string ReturnValue;

        public WindowEventsExtended(string initial="") {
            InitializeComponent();
            cmbLogTypeExtended.ItemsSource = ExtendedItems;
            cmbLogTypeExtended.Text = initial;
        }

        private void btnSelect_Click(object sender, RoutedEventArgs e) {
            ReturnValue = cmbLogTypeExtended.Text;

            this.DialogResult = true;
            this.Close();
        }

        /// <summary>
        /// C:\Windows\System32\winevt\Logs
        /// Use "wevtutil el" to get a list.
        /// Had to scan through all of them to weed out any that returned "SYS_NOT_SUPPORTED"
        /// </summary>

        public static List<string> ExtendedItems = new List<string>() {
            "Application",
            "ApplicationKaseya Scripting",
            "ForwardedEvents",
            //"HP Analytics",
            //"HP Sure Start",
            //"HPNotifications Application",
            "HardwareEvents",
            //"Intel-SST-BUS/Debug",
            //"IntelAudioServiceLog",
            "Internet Explorer",
            "Key Management Service",
            "Microsoft-AppV-Client/Admin",
            "Microsoft-AppV-Client/Operational",
            "Microsoft-AppV-Client/Virtual Applications",
            "Microsoft-Client-Licensing-Platform/Admin",
            "Microsoft-ServiceBus-Client/Admin",
            "Microsoft-ServiceBus-Client/Operational",
            "Microsoft-User Experience Virtualization-Agent Driver/Operational",
            "Microsoft-User Experience Virtualization-App Agent/Operational",
            "Microsoft-User Experience Virtualization-IPC/Operational",
            "Microsoft-User Experience Virtualization-SQM Uploader/Operational",
            "Microsoft-Windows-AAD/Operational",
            "Microsoft-Windows-ASN1/Operational",
            "Microsoft-Windows-All-User-Install-Agent/Admin",
            "Microsoft-Windows-AllJoyn/Operational",
            "Microsoft-Windows-AppHost/Admin",
            "Microsoft-Windows-AppID/Operational",
            "Microsoft-Windows-AppLocker/EXE and DLL",
            "Microsoft-Windows-AppLocker/MSI and Script",
            "Microsoft-Windows-AppLocker/Packaged app-Deployment",
            "Microsoft-Windows-AppLocker/Packaged app-Execution",
            "Microsoft-Windows-AppModel-Runtime/Admin",
            "Microsoft-Windows-AppReadiness/Admin",
            "Microsoft-Windows-AppXDeployment/Operational",
            "Microsoft-Windows-AppXDeploymentServer/Operational",
            "Microsoft-Windows-AppXDeploymentServer/Restricted",
            "Microsoft-Windows-ApplicabilityEngine/Operational",
            "Microsoft-Windows-Application Server-Applications/Admin",
            "Microsoft-Windows-Application Server-Applications/Operational",
            "Microsoft-Windows-Application-Experience/Program-Compatibility-Assistant",
            "Microsoft-Windows-Application-Experience/Program-Compatibility-Troubleshooter",
            "Microsoft-Windows-Application-Experience/Program-Inventory",
            "Microsoft-Windows-Application-Experience/Program-Telemetry",
            "Microsoft-Windows-Application-Experience/Steps-Recorder",
            "Microsoft-Windows-AppxPackaging/Operational",
            "Microsoft-Windows-AssignedAccess/Admin",
            "Microsoft-Windows-AssignedAccess/Operational",
            "Microsoft-Windows-AssignedAccessBroker/Admin",
            "Microsoft-Windows-AssignedAccessBroker/Operational",
            "Microsoft-Windows-Audio/CaptureMonitor",
            "Microsoft-Windows-Audio/GlitchDetection",
            "Microsoft-Windows-Audio/Informational",
            "Microsoft-Windows-Audio/Operational",
            "Microsoft-Windows-Audio/PlaybackManager",
            "Microsoft-Windows-Authentication User Interface/Operational",
            "Microsoft-Windows-Authentication/AuthenticationPolicyFailures-DomainController",
            "Microsoft-Windows-Authentication/ProtectedUser-Client",
            "Microsoft-Windows-Authentication/ProtectedUserFailures-DomainController",
            "Microsoft-Windows-Authentication/ProtectedUserSuccesses-DomainController",
            "Microsoft-Windows-BackgroundTaskInfrastructure/Operational",
            "Microsoft-Windows-BackgroundTransfer-ContentPrefetcher/Operational",
            "Microsoft-Windows-Backup",
            "Microsoft-Windows-Base-Filtering-Engine-Connections/Operational",
            "Microsoft-Windows-Base-Filtering-Engine-Resource-Flows/Operational",
            "Microsoft-Windows-Biometrics/Operational",
            "Microsoft-Windows-BitLocker-DrivePreparationTool/Admin",
            "Microsoft-Windows-BitLocker-DrivePreparationTool/Operational",
            "Microsoft-Windows-BitLocker/BitLocker Management",
            "Microsoft-Windows-BitLocker/BitLocker Operational",
            "Microsoft-Windows-Bits-Client/Analytic",
            "Microsoft-Windows-Bluetooth-BthLEPrepairing/Operational",
            "Microsoft-Windows-Bluetooth-Bthmini/Operational",
            "Microsoft-Windows-Bluetooth-MTPEnum/Operational",
            "Microsoft-Windows-Bluetooth-Policy/Operational",
            "Microsoft-Windows-BranchCache/Operational",
            "Microsoft-Windows-BranchCacheSMB/Operational",
            "Microsoft-Windows-CAPI2/Operational",
            "Microsoft-Windows-CertPoleEng/Operational",
            "Microsoft-Windows-CertificateServicesClient-CredentialRoaming/Operational",
            "Microsoft-Windows-CertificateServicesClient-Lifecycle-System/Operational",
            "Microsoft-Windows-CertificateServicesClient-Lifecycle-User/Operational",
            "Microsoft-Windows-Cleanmgr/Diagnostic",
            "Microsoft-Windows-CloudStore/Debug",
            "Microsoft-Windows-CloudStore/Operational",
            "Microsoft-Windows-CodeIntegrity/Operational",
            "Microsoft-Windows-Compat-Appraiser/Operational",
            "Microsoft-Windows-Containers-BindFlt/Operational",
            "Microsoft-Windows-Containers-Wcifs/Operational",
            "Microsoft-Windows-Containers-Wcnfs/Operational",
            "Microsoft-Windows-CoreApplication/Operational",
            "Microsoft-Windows-CoreSystem-SmsRouter-Events/Operational",
            "Microsoft-Windows-CorruptedFileRecovery-Client/Operational",
            "Microsoft-Windows-CorruptedFileRecovery-Server/Operational",
            "Microsoft-Windows-Crypto-DPAPI/BackUpKeySvc",
            "Microsoft-Windows-Crypto-DPAPI/Debug",
            "Microsoft-Windows-Crypto-DPAPI/Operational",
            "Microsoft-Windows-Crypto-NCrypt/Operational",
            "Microsoft-Windows-DAL-Provider/Operational",
            "Microsoft-Windows-DNS-Client/Operational",
            "Microsoft-Windows-DSC/Admin",
            "Microsoft-Windows-DSC/Operational",
            "Microsoft-Windows-DataIntegrityScan/Admin",
            "Microsoft-Windows-DataIntegrityScan/CrashRecovery",
            "Microsoft-Windows-DateTimeControlPanel/Operational",
            "Microsoft-Windows-Deduplication/Diagnostic",
            "Microsoft-Windows-Deduplication/Operational",
            "Microsoft-Windows-Deduplication/Scrubbing",
            "Microsoft-Windows-DeviceGuard/Operational",
            "Microsoft-Windows-DeviceManagement-Enterprise-Diagnostics-Provider/Admin",
            "Microsoft-Windows-DeviceManagement-Enterprise-Diagnostics-Provider/Operational",
            "Microsoft-Windows-DeviceSetupManager/Admin",
            "Microsoft-Windows-DeviceSetupManager/Operational",
            "Microsoft-Windows-DeviceSync/Operational",
            "Microsoft-Windows-DeviceUpdateAgent/Operational",
            "Microsoft-Windows-Devices-Background/Operational",
            "Microsoft-Windows-Dhcp-Client/Admin",
            "Microsoft-Windows-Dhcp-Client/Operational",
            "Microsoft-Windows-Dhcpv6-Client/Admin",
            "Microsoft-Windows-Dhcpv6-Client/Operational",
            "Microsoft-Windows-Diagnosis-DPS/Operational",
            "Microsoft-Windows-Diagnosis-PCW/Operational",
            "Microsoft-Windows-Diagnosis-PLA/Operational",
            "Microsoft-Windows-Diagnosis-Scheduled/Operational",
            "Microsoft-Windows-Diagnosis-Scripted/Admin",
            "Microsoft-Windows-Diagnosis-Scripted/Operational",
            "Microsoft-Windows-Diagnosis-ScriptedDiagnosticsProvider/Operational",
            "Microsoft-Windows-Diagnostics-Networking/Operational",
            "Microsoft-Windows-Diagnostics-Performance/Operational",
            "Microsoft-Windows-DiskDiagnostic/Operational",
            "Microsoft-Windows-DiskDiagnosticDataCollector/Operational",
            "Microsoft-Windows-DiskDiagnosticResolver/Operational",
            "Microsoft-Windows-DisplayColorCalibration/Operational",
            "Microsoft-Windows-DriverFrameworks-UserMode/Operational",
            "Microsoft-Windows-DxgKrnl-Admin",
            "Microsoft-Windows-DxgKrnl-Operational",
            "Microsoft-Windows-EDP-Application-Learning/Admin",
            "Microsoft-Windows-EDP-Audit-Regular/Admin",
            "Microsoft-Windows-EDP-Audit-TCB/Admin",
            "Microsoft-Windows-ESE/Operational",
            "Microsoft-Windows-EapHost/Operational",
            "Microsoft-Windows-EapMethods-RasChap/Operational",
            "Microsoft-Windows-EapMethods-RasTls/Operational",
            "Microsoft-Windows-EapMethods-Sim/Operational",
            "Microsoft-Windows-EapMethods-Ttls/Operational",
            "Microsoft-Windows-Energy-Estimation-Engine/EventLog",
            "Microsoft-Windows-EventCollector/Operational",
            "Microsoft-Windows-FMS/Operational",
            "Microsoft-Windows-Fault-Tolerant-Heap/Operational",
            "Microsoft-Windows-FeatureConfiguration/Operational",
            "Microsoft-Windows-FileHistory-Core/WHC",
            "Microsoft-Windows-FileHistory-Engine/BackupLog",
            "Microsoft-Windows-Folder Redirection/Operational",
            "Microsoft-Windows-Forwarding/Operational",
            "Microsoft-Windows-GenericRoaming/Admin",
            "Microsoft-Windows-GroupPolicy/Operational",
            "Microsoft-Windows-HelloForBusiness/Operational",
            "Microsoft-Windows-Help/Operational",
            "Microsoft-Windows-HomeGroup Control Panel/Operational",
            "Microsoft-Windows-HomeGroup Listener Service/Operational",
            "Microsoft-Windows-HomeGroup Provider Service/Operational",
            "Microsoft-Windows-HotspotAuth/Operational",
            "Microsoft-Windows-HttpService/Log",
            "Microsoft-Windows-HttpService/Trace",
            "Microsoft-Windows-Hyper-V-Guest-Drivers/Admin",
            "Microsoft-Windows-Hyper-V-Guest-Drivers/Operational",
            "Microsoft-Windows-Hyper-V-Hypervisor-Admin",
            "Microsoft-Windows-Hyper-V-Hypervisor-Operational",
            "Microsoft-Windows-Hyper-V-VID-Admin",
            "Microsoft-Windows-IKE/Operational",
            "Microsoft-Windows-IPxlatCfg/Operational",
            "Microsoft-Windows-IdCtrls/Operational",
            "Microsoft-Windows-International-RegionalOptionsControlPanel/Operational",
            "Microsoft-Windows-International/Operational",
            "Microsoft-Windows-Iphlpsvc/Operational",
            "Microsoft-Windows-KdsSvc/Operational",
            "Microsoft-Windows-Kerberos/Operational",
            "Microsoft-Windows-Kernel-ApphelpCache/Operational",
            "Microsoft-Windows-Kernel-Boot/Operational",
            "Microsoft-Windows-Kernel-EventTracing/Admin",
            "Microsoft-Windows-Kernel-IO/Operational",
            "Microsoft-Windows-Kernel-LiveDump/Operational",
            "Microsoft-Windows-Kernel-PnP/Configuration",
            "Microsoft-Windows-Kernel-PnP/Driver Watchdog",
            "Microsoft-Windows-Kernel-Power/Thermal-Operational",
            "Microsoft-Windows-Kernel-ShimEngine/Operational",
            "Microsoft-Windows-Kernel-StoreMgr/Operational",
            "Microsoft-Windows-Kernel-WDI/Operational",
            "Microsoft-Windows-Kernel-WHEA/Errors",
            "Microsoft-Windows-Kernel-WHEA/Operational",
            "Microsoft-Windows-KeyboardFilter/Admin",
            "Microsoft-Windows-KeyboardFilter/Operational",
            "Microsoft-Windows-KeyboardFilter/Performance",
            "Microsoft-Windows-Known Folders API Service",
            "Microsoft-Windows-LSA/Operational",
            "Microsoft-Windows-LanguagePackSetup/Operational",
            "Microsoft-Windows-LinkLayerDiscoveryProtocol/Operational",
            "Microsoft-Windows-LiveId/Operational",
            "Microsoft-Windows-MSPaint/Admin",
            "Microsoft-Windows-MUI/Admin",
            "Microsoft-Windows-MUI/Operational",
            "Microsoft-Windows-MediaFoundation-Performance/SARStreamResource",
            "Microsoft-Windows-MemoryDiagnostics-Results/Debug",
            "Microsoft-Windows-Mobile-Broadband-Experience-Parser-Task/Operational",
            "Microsoft-Windows-ModernDeployment-Diagnostics-Provider/Admin",
            "Microsoft-Windows-ModernDeployment-Diagnostics-Provider/Autopilot",
            "Microsoft-Windows-ModernDeployment-Diagnostics-Provider/ManagementService",
            "Microsoft-Windows-Mprddm/Operational",
            "Microsoft-Windows-NCSI/Operational",
            "Microsoft-Windows-NDIS/Operational",
            "Microsoft-Windows-NTLM/Operational",
            "Microsoft-Windows-Ncasvc/Operational",
            "Microsoft-Windows-NcdAutoSetup/Operational",
            "Microsoft-Windows-NdisImPlatform/Operational",
            "Microsoft-Windows-NetworkLocationWizard/Operational",
            "Microsoft-Windows-NetworkProfile/Operational",
            "Microsoft-Windows-NetworkProvider/Operational",
            "Microsoft-Windows-NetworkProvisioning/Operational",
            "Microsoft-Windows-NlaSvc/Operational",
            "Microsoft-Windows-Ntfs/Operational",
            "Microsoft-Windows-Ntfs/WHC",
            "Microsoft-Windows-OOBE-Machine-DUI/Operational",
            "Microsoft-Windows-OfflineFiles/Operational",
            "Microsoft-Windows-OneBackup/Debug",
            "Microsoft-Windows-OneX/Operational",
            "Microsoft-Windows-OtpCredentialProvider/Operational",
            "Microsoft-Windows-PackageStateRoaming/Operational",
            "Microsoft-Windows-ParentalControls/Operational",
            "Microsoft-Windows-Partition/Diagnostic",
            "Microsoft-Windows-PerceptionRuntime/Operational",
            "Microsoft-Windows-PerceptionSensorDataService/Operational",
            "Microsoft-Windows-PersistentMemory-Nvdimm/Operational",
            "Microsoft-Windows-PersistentMemory-PmemDisk/Operational",
            "Microsoft-Windows-PersistentMemory-ScmBus/Certification",
            "Microsoft-Windows-PersistentMemory-ScmBus/Operational",
            "Microsoft-Windows-Policy/Operational",
            "Microsoft-Windows-PowerShell-DesiredStateConfiguration-FileDownloadManager/Operational",
            "Microsoft-Windows-PowerShell/Admin",
            "Microsoft-Windows-PowerShell/Operational",
            "Microsoft-Windows-PrintBRM/Admin",
            "Microsoft-Windows-PrintService/Admin",
            "Microsoft-Windows-PrintService/Operational",
            "Microsoft-Windows-Privacy-Auditing/Operational",
            "Microsoft-Windows-Program-Compatibility-Assistant/Analytic",
            "Microsoft-Windows-Program-Compatibility-Assistant/CompatAfterUpgrade",
            "Microsoft-Windows-Provisioning-Diagnostics-Provider/Admin",
            "Microsoft-Windows-Provisioning-Diagnostics-Provider/AutoPilot",
            "Microsoft-Windows-Provisioning-Diagnostics-Provider/ManagementService",
            "Microsoft-Windows-Proximity-Common/Diagnostic",
            "Microsoft-Windows-PushNotification-Platform/Admin",
            "Microsoft-Windows-PushNotification-Platform/Operational",
            "Microsoft-Windows-RRAS/Operational",
            "Microsoft-Windows-RasAgileVpn/Operational",
            "Microsoft-Windows-ReFS/Operational",
            "Microsoft-Windows-ReadyBoost/Operational",
            "Microsoft-Windows-ReadyBoostDriver/Operational",
            "Microsoft-Windows-Regsvr32/Operational",
            "Microsoft-Windows-RemoteApp and Desktop Connections/Admin",
            "Microsoft-Windows-RemoteApp and Desktop Connections/Operational",
            "Microsoft-Windows-RemoteAssistance/Admin",
            "Microsoft-Windows-RemoteAssistance/Operational",
            "Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Admin",
            "Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational",
            "Microsoft-Windows-RemoteDesktopServices-RemoteFX-Synth3dvsc/Admin",
            "Microsoft-Windows-RemoteDesktopServices-SessionServices/Operational",
            "Microsoft-Windows-Remotefs-Rdbss/Operational",
            "Microsoft-Windows-Resource-Exhaustion-Detector/Operational",
            "Microsoft-Windows-Resource-Exhaustion-Resolver/Operational",
            "Microsoft-Windows-RestartManager/Operational",
            "Microsoft-Windows-RetailDemo/Admin",
            "Microsoft-Windows-RetailDemo/Operational",
            "Microsoft-Windows-SENSE/Operational",
            "Microsoft-Windows-SMBClient/Operational",
            "Microsoft-Windows-SMBDirect/Admin",
            "Microsoft-Windows-SMBServer/Audit",
            "Microsoft-Windows-SMBServer/Connectivity",
            "Microsoft-Windows-SMBServer/Operational",
            "Microsoft-Windows-SMBServer/Security",
            "Microsoft-Windows-SMBWitnessClient/Admin",
            "Microsoft-Windows-SMBWitnessClient/Informational",
            "Microsoft-Windows-SearchUI/Operational",
            "Microsoft-Windows-SecureAssessment/Operational",
            "Microsoft-Windows-Security-Adminless/Operational",
            "Microsoft-Windows-Security-Audit-Configuration-Client/Operational",
            "Microsoft-Windows-Security-EnterpriseData-FileRevocationManager/Operational",
            "Microsoft-Windows-Security-ExchangeActiveSyncProvisioning/Operational",
            "Microsoft-Windows-Security-IdentityListener/Operational",
            "Microsoft-Windows-Security-LessPrivilegedAppContainer/Operational",
            "Microsoft-Windows-Security-Mitigations/KernelMode",
            "Microsoft-Windows-Security-Mitigations/UserMode",
            "Microsoft-Windows-Security-Netlogon/Operational",
            "Microsoft-Windows-Security-SPP-UX-GenuineCenter-Logging/Operational",
            "Microsoft-Windows-Security-SPP-UX-Notifications/ActionCenter",
            "Microsoft-Windows-Security-UserConsentVerifier/Audit",
            "Microsoft-Windows-SecurityMitigationsBroker/Admin",
            "Microsoft-Windows-SecurityMitigationsBroker/Operational",
            "Microsoft-Windows-SenseIR/Operational",
            "Microsoft-Windows-ServiceReportingApi/Debug",
            "Microsoft-Windows-SettingSync-Azure/Debug",
            "Microsoft-Windows-SettingSync-Azure/Operational",
            "Microsoft-Windows-SettingSync-OneDrive/Debug",
            "Microsoft-Windows-SettingSync-OneDrive/Operational",
            "Microsoft-Windows-SettingSync/Debug",
            "Microsoft-Windows-SettingSync/Operational",
            "Microsoft-Windows-Shell-ConnectedAccountState/ActionCenter",
            "Microsoft-Windows-Shell-Core/ActionCenter",
            "Microsoft-Windows-Shell-Core/AppDefaults",
            "Microsoft-Windows-Shell-Core/LogonTasksChannel",
            "Microsoft-Windows-Shell-Core/Operational",
            "Microsoft-Windows-ShellCommon-StartLayoutPopulation/Operational",
            "Microsoft-Windows-SmartCard-Audit/Authentication",
            "Microsoft-Windows-SmartCard-DeviceEnum/Operational",
            "Microsoft-Windows-SmartCard-TPM-VCard-Module/Admin",
            "Microsoft-Windows-SmartCard-TPM-VCard-Module/Operational",
            "Microsoft-Windows-SmartScreen/Debug",
            "Microsoft-Windows-SmbClient/Audit",
            "Microsoft-Windows-SmbClient/Connectivity",
            "Microsoft-Windows-SmbClient/Security",
            "Microsoft-Windows-StateRepository/Operational",
            "Microsoft-Windows-StateRepository/Restricted",
            "Microsoft-Windows-Storage-ATAPort/Admin",
            "Microsoft-Windows-Storage-ATAPort/Operational",
            "Microsoft-Windows-Storage-ClassPnP/Admin",
            "Microsoft-Windows-Storage-ClassPnP/Operational",
            "Microsoft-Windows-Storage-Disk/Admin",
            "Microsoft-Windows-Storage-Disk/Operational",
            "Microsoft-Windows-Storage-Storport/Admin",
            "Microsoft-Windows-Storage-Storport/Health",
            "Microsoft-Windows-Storage-Storport/Operational",
            "Microsoft-Windows-Storage-Tiering/Admin",
            "Microsoft-Windows-StorageManagement/Operational",
            "Microsoft-Windows-StorageSettings/Diagnostic",
            "Microsoft-Windows-StorageSpaces-Driver/Diagnostic",
            "Microsoft-Windows-StorageSpaces-Driver/Operational",
            "Microsoft-Windows-StorageSpaces-ManagementAgent/WHC",
            "Microsoft-Windows-StorageSpaces-SpaceManager/Diagnostic",
            "Microsoft-Windows-StorageSpaces-SpaceManager/Operational",
            "Microsoft-Windows-Store/Operational",
            "Microsoft-Windows-Storsvc/Diagnostic",
            "Microsoft-Windows-SystemSettingsThreshold/Operational",
            "Microsoft-Windows-TCPIP/Operational",
            "Microsoft-Windows-TZSync/Operational",
            "Microsoft-Windows-TZUtil/Operational",
            "Microsoft-Windows-TaskScheduler/Maintenance",
            "Microsoft-Windows-TaskScheduler/Operational",
            "Microsoft-Windows-TerminalServices-ClientUSBDevices/Admin",
            "Microsoft-Windows-TerminalServices-ClientUSBDevices/Operational",
            "Microsoft-Windows-TerminalServices-LocalSessionManager/Admin",
            "Microsoft-Windows-TerminalServices-LocalSessionManager/Operational",
            "Microsoft-Windows-TerminalServices-PnPDevices/Admin",
            "Microsoft-Windows-TerminalServices-PnPDevices/Operational",
            "Microsoft-Windows-TerminalServices-Printers/Admin",
            "Microsoft-Windows-TerminalServices-Printers/Operational",
            "Microsoft-Windows-TerminalServices-RDPClient/Operational",
            "Microsoft-Windows-TerminalServices-RemoteConnectionManager/Admin",
            "Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational",
            "Microsoft-Windows-TerminalServices-ServerUSBDevices/Admin",
            "Microsoft-Windows-TerminalServices-ServerUSBDevices/Operational",
            "Microsoft-Windows-Time-Service-PTP-Provider/PTP-Operational",
            "Microsoft-Windows-Time-Service/Operational",
            "Microsoft-Windows-Troubleshooting-Recommended/Admin",
            "Microsoft-Windows-Troubleshooting-Recommended/Operational",
            "Microsoft-Windows-UAC-FileVirtualization/Operational",
            "Microsoft-Windows-UAC/Operational",
            "Microsoft-Windows-USBVideo/Analytic",
            "Microsoft-Windows-UniversalTelemetryClient/Operational",
            "Microsoft-Windows-User Control Panel/Operational",
            "Microsoft-Windows-User Device Registration/Admin",
            "Microsoft-Windows-User Profile Service/Operational",
            "Microsoft-Windows-User-Loader/Operational",
            "Microsoft-Windows-UserPnp/ActionCenter",
            "Microsoft-Windows-UserPnp/DeviceInstall",
            "Microsoft-Windows-VDRVROOT/Operational",
            "Microsoft-Windows-VHDMP-Operational",
            "Microsoft-Windows-VPN-Client/Operational",
            "Microsoft-Windows-VPN/Operational",
            "Microsoft-Windows-VerifyHardwareSecurity/Admin",
            "Microsoft-Windows-VerifyHardwareSecurity/Operational",
            "Microsoft-Windows-Volume/Diagnostic",
            "Microsoft-Windows-VolumeSnapshot-Driver/Operational",
            "Microsoft-Windows-WDAG-PolicyEvaluator-CSP/Operational",
            "Microsoft-Windows-WDAG-PolicyEvaluator-GP/Operational",
            "Microsoft-Windows-WEPHOSTSVC/Operational",
            "Microsoft-Windows-WFP/Operational",
            "Microsoft-Windows-WLAN-AutoConfig/Operational",
            "Microsoft-Windows-WMI-Activity/Operational",
            "Microsoft-Windows-WMPNSS-Service/Operational",
            "Microsoft-Windows-WPD-ClassInstaller/Operational",
            "Microsoft-Windows-WPD-CompositeClassDriver/Operational",
            "Microsoft-Windows-WPD-MTPClassDriver/Operational",
            "Microsoft-Windows-WWAN-SVC-Events/Operational",
            "Microsoft-Windows-Wcmsvc/Operational",
            "Microsoft-Windows-WebAuth/Operational",
            "Microsoft-Windows-WebAuthN/Operational",
            "Microsoft-Windows-WebIO-NDF/Diagnostic",
            "Microsoft-Windows-Win32k/Operational",
            "Microsoft-Windows-WinHTTP-NDF/Diagnostic",
            "Microsoft-Windows-WinINet-Capture/Analytic",
            "Microsoft-Windows-WinNat/Oper",
            "Microsoft-Windows-WinRM/Operational",
            "Microsoft-Windows-Windows Defender/Operational",
            "Microsoft-Windows-Windows Defender/WHC",
            "Microsoft-Windows-Windows Firewall With Advanced Security/ConnectionSecurity",
            "Microsoft-Windows-Windows Firewall With Advanced Security/ConnectionSecurityVerbose",
            "Microsoft-Windows-Windows Firewall With Advanced Security/Firewall",
            "Microsoft-Windows-Windows Firewall With Advanced Security/FirewallDiagnostics",
            "Microsoft-Windows-Windows Firewall With Advanced Security/FirewallVerbose",
            "Microsoft-Windows-WindowsBackup/ActionCenter",
            "Microsoft-Windows-WindowsColorSystem/Operational",
            "Microsoft-Windows-WindowsSystemAssessmentTool/Operational",
            "Microsoft-Windows-WindowsUIImmersive/Operational",
            "Microsoft-Windows-WindowsUpdateClient/Operational",
            "Microsoft-Windows-Winlogon/Operational",
            "Microsoft-Windows-Winsock-AFD/Operational",
            "Microsoft-Windows-Winsock-NameResolution/Operational",
            "Microsoft-Windows-Winsock-WS2HELP/Operational",
            "Microsoft-Windows-Wired-AutoConfig/Operational",
            "Microsoft-Windows-Wordpad/Admin",
            "Microsoft-Windows-WorkFolders/Operational",
            "Microsoft-Windows-WorkFolders/WHC",
            "Microsoft-Windows-Workplace Join/Admin",
            "Microsoft-Windows-glcnd/Admin",
            "Microsoft-Windows-wmbclass/Trace",
            "Microsoft-WindowsPhone-Connectivity-WiFiConnSvc-Channel",
            "Network Isolation Operational",
            "OAlerts",
            "OneApp_IGCC",
            "OpenSSH/Admin",
            "OpenSSH/Operational",
            "SMSApi",
            "Security",
            "Setup",
            "System",
            "Windows Networking Vpn Plugin Platform/Operational",
            "Windows Networking Vpn Plugin Platform/OperationalVerbose",
            "Windows PowerShell"
        };
    }
}
